fullscreen=true
winResizable=false
anyAltToggleFS=true
smoothScaling=false
vsync=false
subImageFix=false
enableBlitting=false
frameSkip=false
fixedAspectRatio=false
fixedFramerate=40

# DO NOT TOUCH
iconPath=icon.png
dataPathOrg=freebirdgames
dataPathApp=tothemoon
preloadScript=preload/ruby18_comp.rb
preloadScript=preload/win32_wrap.rb
preloadScript=preload/utils.dll.rb
fontSub=Arial>Open Sans
fontSub=Times New Roman>Open Sans
fontSub=Tahoma>Open Sans
fontSub=Ariel>Open Sans
fontSub=Times>Open Sans
